blog:
    resource: "@BlogBundle/Controller/"
    type:     annotation
    prefix:   /

app:
    resource: '@AppBundle/Controller/'
    type: annotation
login:
    path:     /login
    defaults: { _controller: BlogBundle:Security:login }
user_registration:
    path:     /register
    defaults: { _controller: BlogBundle:Registration:register }